# Generated by Django 5.2.17 on 2026-09-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply_byAI',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='at_received',
            field=models.DateTimeField(),
        ),
    ]
